### ISSUE TITLE
Handle simultaneous detections in getFirstLast() fxn

### ISSUE THREAD

**Issue by Myfanwy** [Myfanwy/fishtrackr#11]
@noamross the getFirstLast() function (currently poorly doc'd) is supposed to extract a fish's first and last location and calculate travel time and total distance (`reachdistance`) column.  It does this, but sometimes a fish has simultaneous detections at locations where receivers are close together (example: `BC_joint' and 'BC_joint2` stations, see `alljuvtt` dataset (built-in)).

so, when you run `getFirstLast(alljuvtt)`and store it to an object, you'll note that some TagIDs have multiple entries (each TagID should only have a single entry).  Ultimately this is a data quality issue (need to first write functions that check for duplicate arrival/departures), but for now, how can the `getFirstLast()` function be modified to only keep the detection that corresponds to the right reach distance (in this case, the greatest reach distance)?

**Comment by noamross** [comment]
This is the simplest approach I thought of, though I don't know how it would handle some edge cases.  There were plenty of cases where the release station had two distances for stations of the same name. Does that make sense?

**Comment by Myfanwy** [comment]
Thanks, I'll take a look at it first thing tomorrow!  Yes, that makes sense, although I know it's odd - some are because fish travel from different release locations, and some are because the receivers are gated... Chipps has a gated array that should really be called Chipps1 and Chipps2, but there are some cases where a fish is only detected at one of them, and either one counts as Chipps (it's the furthest downstream location).... it's a bit of a mess because the array is being used for a lot of different objectives.

**Comment by Myfanwy** [comment]
Closed with commit e68210f
